services:
  django:
    restart: unless-stopped
    build:
      context: ./project_maker
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8000
        # published: 8000 # uncomment for local dev
    environment:
      - DEBUG=False # set to "True" for local dev
    #deploy:
    #  resources:
    #    reservations:
    #      memory: 256M
