# Generated by Django 5.2 on 2025-11-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('WEB', 'Website'), ('APP', 'Android App'), ('GAME', 'Game'), ('MODEL', '3D Model')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('launch_date', models.DateField()),
                ('is_premium', models.BooleanField(default=False)),
                ('template_available', models.BooleanField(default=False)),
                ('achievement_tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('user_tags', models.CharField(blank=True, help_text='Comma-separated user rewards or categories', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
            ],
        ),
    ]
