# Generated by Django 5.2 on 2025-05-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='category',
            field=models.CharField(default='achivments', max_length=50),
            preserve_default=False,
        ),
    ]
