# Generated by Django 5.2 on 2025-05-13 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='achieve',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achieve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.achievement'),
            preserve_default=False,
        ),
    ]
