# Generated by Django 5.2 on 2025-05-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usertag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fear_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(default='Free', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fear_level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.fearlevel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.membership'),
        ),
    ]
