# Generated by Django 5.2 on 2025-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_userachievement_achieve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='joined_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
