# Generated by Django 5.2 on 2025-05-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_fearlevel_membership_alter_userprofile_fear_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fearlevel',
            old_name='fear_level',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='membership',
            new_name='name',
        ),
    ]
