# Generated by Django 5.2 on 2025-05-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_userexperience_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
