# Generated by Django 5.2 on 2025-05-11 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_fear_level_fearlevel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fear_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.fearlevel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.membership'),
        ),
    ]
