# Generated by Django 5.2 on 2025-05-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_userprofile_fear_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fear_level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership',
            field=models.CharField(default='Free', max_length=20),
        ),
        migrations.DeleteModel(
            name='FearLevel',
        ),
        migrations.DeleteModel(
            name='MemberShip',
        ),
    ]
