# Generated by Django 5.2 on 2025-05-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_experience_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexperience',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
