# Generated by Django 5.2 on 2025-11-21 08:57

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_userexperience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fear_level',
            field=models.ForeignKey(default=dashboard.models.get_default_fear_level, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.fearlevel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership',
            field=models.ForeignKey(default=dashboard.models.get_default_membership, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.membership'),
        ),
    ]
