# Generated by Django 5.2 on 2025-05-11 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_userprofile_fear_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Free', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fear_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.fearlevel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.membership'),
        ),
    ]
