# Generated by Django 5.2 on 2025-05-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_userprofile_fear_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fearlevel',
            name='description',
            field=models.TextField(default='helo', max_length=100),
            preserve_default=False,
        ),
    ]
