# Generated by Django 5.2 on 2025-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_fearlevel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.TextField(default='Free Hunter', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='perk',
            field=models.TextField(default=['pr'], max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(default='Free Haunter', max_length=20),
        ),
    ]
