# Generated by Django 5.2 on 2025-05-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_achievement_date_earned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='title',
            new_name='name',
        ),
    ]
