# Generated by Django 5.2 on 2025-05-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_number', models.CharField(max_length=10)),
                ('user_subject', models.CharField(max_length=200)),
                ('user_message', models.CharField(max_length=2000)),
                ('user_subscribe', models.BooleanField(default=False)),
            ],
        ),
    ]
