# Generated by Django 5.2 on 2025-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackcontactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=100)),
                ('rating', models.IntegerField()),
                ('review_message', models.CharField(max_length=2000)),
            ],
        ),
    ]
